version: 2
project_name: autopus-bridge

before:
  hooks:
    - go mod tidy

builds:
  # autopus-bridge: 메인 CLI 바이너리
  - id: autopus-bridge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

  # autopus-mcp-server: MCP 서버 독립 바이너리 (Claude Code 플러그인용)
  - id: autopus-mcp-server
    binary: autopus-mcp-server
    main: ./cmd/mcp-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  # autopus-bridge 아카이브
  - id: autopus-bridge
    builds:
      - autopus-bridge
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

  # autopus-mcp-server 아카이브
  - id: autopus-mcp-server
    builds:
      - autopus-mcp-server
    formats:
      - tar.gz
    name_template: "autopus-mcp-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

brews:
  # autopus-bridge Homebrew 포뮬러
  - ids:
      - autopus-bridge
    repository:
      owner: insajin
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/insajin/autopus-bridge
    description: "Autopus Local Agent Bridge - Connect local development agents to Autopus platform"
    license: "MIT"
    install: |
      bin.install "autopus-bridge"
    test: |
      system "#{bin}/autopus-bridge", "version"

  # autopus-mcp-server Homebrew 포뮬러
  - ids:
      - autopus-mcp-server
    name: autopus-mcp-server
    repository:
      owner: insajin
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/insajin/autopus-bridge
    description: "Autopus MCP Server - Claude Code MCP plugin for Autopus platform integration"
    license: "MIT"
    install: |
      bin.install "autopus-mcp-server"
    test: |
      assert_predicate bin/"autopus-mcp-server", :exist?
