package hook

import (
	"context"
	"encoding/json"
	"io"
	"net/http"

	"github.com/google/uuid"
	"github.com/rs/zerolog"
)

// HookRequest represents parsed PreToolUse hook data from Claude Code.
// When Claude Code fires a hook, it passes tool information on stdin;
// for HTTP-based hooks the body IS that stdin data forwarded via curl.
type HookRequest struct {
	SessionID  string          `json:"session_id"`
	ToolName   string          `json:"tool_name"`
	ToolInput  json.RawMessage `json:"tool_input"`
	ApprovalID string          `json:"-"` // generated by handler, not from JSON
}

// HookResponse is what the hook HTTP endpoint returns to the curl script.
// The calling script inspects the "decision" field:
//   - "allow"  -> script exits 0 (Claude Code proceeds)
//   - "deny"   -> script exits 2 (Claude Code blocks the tool)
type HookResponse struct {
	Decision string `json:"decision"`           // "allow" or "deny"
	Reason   string `json:"reason,omitempty"`    // explanation for deny
	ID       string `json:"approval_id,omitempty"` // the assigned approval ID
}

// OnApprovalFunc is the callback signature invoked when a PreToolUse
// request arrives. Implementations typically relay the request to a
// WebSocket client for user-facing approval UI.
type OnApprovalFunc func(ctx context.Context, req HookRequest)

// HookHandler processes HTTP requests from Claude Code hook scripts.
type HookHandler struct {
	approvalMgr *ApprovalManager
	onApproval  OnApprovalFunc
	logger      zerolog.Logger
}

// HookHandlerOption configures a HookHandler.
type HookHandlerOption func(*HookHandler)

// WithOnApproval sets the callback invoked when a PreToolUse approval
// request is received. The callback runs in a separate goroutine so it
// does not block the approval flow.
func WithOnApproval(fn OnApprovalFunc) HookHandlerOption {
	return func(h *HookHandler) {
		h.onApproval = fn
	}
}

// WithHandlerLogger sets the logger for the handler.
func WithHandlerLogger(logger zerolog.Logger) HookHandlerOption {
	return func(h *HookHandler) {
		h.logger = logger
	}
}

// NewHookHandler creates a HookHandler backed by the given ApprovalManager.
func NewHookHandler(approvalMgr *ApprovalManager, opts ...HookHandlerOption) *HookHandler {
	h := &HookHandler{
		approvalMgr: approvalMgr,
		logger:      zerolog.Nop(),
	}
	for _, opt := range opts {
		opt(h)
	}
	h.logger = h.logger.With().Str("component", "hook-handler").Logger()
	return h
}

// HandlePreToolUse processes a PreToolUse hook request.
//
// Flow:
//  1. Read and parse the request body (tool info from Claude Code).
//  2. Generate a unique approval ID.
//  3. Fire the onApproval callback asynchronously (for WebSocket relay).
//  4. Block on ApprovalManager.RequestApproval until a decision arrives.
//  5. Return JSON: {"decision":"allow"} or {"decision":"deny","reason":"..."}.
func (h *HookHandler) HandlePreToolUse(w http.ResponseWriter, r *http.Request) {
	body, err := io.ReadAll(r.Body)
	if err != nil {
		h.logger.Error().Err(err).Msg("failed to read request body")
		writeJSON(w, http.StatusBadRequest, HookResponse{
			Decision: "deny",
			Reason:   "failed to read request body",
		})
		return
	}
	defer r.Body.Close()

	var req HookRequest
	if err := json.Unmarshal(body, &req); err != nil {
		h.logger.Error().Err(err).Msg("failed to parse hook request JSON")
		writeJSON(w, http.StatusBadRequest, HookResponse{
			Decision: "deny",
			Reason:   "invalid JSON payload",
		})
		return
	}

	req.ApprovalID = uuid.New().String()

	h.logger.Info().
		Str("approval_id", req.ApprovalID).
		Str("tool_name", req.ToolName).
		Str("session_id", req.SessionID).
		Msg("PreToolUse hook received")

	// Fire approval callback asynchronously so the WebSocket relay
	// does not block the HTTP response path.
	if h.onApproval != nil {
		go h.onApproval(r.Context(), req)
	}

	// Block until a decision arrives or timeout expires.
	decision, err := h.approvalMgr.RequestApproval(r.Context(), req.ApprovalID)

	resp := HookResponse{
		ID: req.ApprovalID,
	}
	if err != nil || !decision.Allow {
		resp.Decision = "deny"
		resp.Reason = decision.Reason
		if resp.Reason == "" && err != nil {
			resp.Reason = err.Error()
		}
	} else {
		resp.Decision = "allow"
	}

	h.logger.Info().
		Str("approval_id", req.ApprovalID).
		Str("decision", resp.Decision).
		Msg("PreToolUse hook responding")

	writeJSON(w, http.StatusOK, resp)
}

// HandlePostToolUse processes a PostToolUse hook notification. It logs
// the tool execution result for audit purposes and always returns 200 OK.
func (h *HookHandler) HandlePostToolUse(w http.ResponseWriter, r *http.Request) {
	body, err := io.ReadAll(r.Body)
	if err != nil {
		h.logger.Error().Err(err).Msg("failed to read PostToolUse body")
		w.WriteHeader(http.StatusOK)
		return
	}
	defer r.Body.Close()

	h.logger.Info().
		RawJSON("payload", body).
		Msg("PostToolUse hook received (audit)")

	w.WriteHeader(http.StatusOK)
}

// writeJSON serialises v to JSON and writes it to the response writer.
func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if err := json.NewEncoder(w).Encode(v); err != nil {
		// Encoding failure after header written; nothing to do but log.
		return
	}
}
